### ISSUE TITLE
Design Rating UI

### ISSUE THREAD

**Issue by jonathanhawleypeters** [jonathanhawleypeters/tunnel-weasel#30]
I'd like to display the overall rating of each card in one consistent way throughout the whole site. I think a number with one decimal place rendered inside a star icon would be good. I'm open to other suggestions.

The component that allows users to rate a card can use the same star icon repeated 5 times, and behave the way it already does when a user submits a rating.

I think we've agreed that we need a new star icon.

**Comment by jesterswilde** [comment]
@jonathanhawleypeters  is this solved?

**Comment by jonathanhawleypeters** [comment]
Yes
